twitter:
  consumer-key: 4SK2ld8rBcWRrNN5dLpDec0hk
  consumer-secret: EYrOhfWU8e6XEW24PWKPvkjRTgjQNKRlRqXmPwD2eIS0dP0kud
  access-token: 233589200-VcXPGyx8D3ZzCj7fpgJf06cbqDETaHHC2LgSuU5s
  access-token-secret: d6kB0cNVnAPwxVqNIYb9gmdQtBpT93hBNoMp6SEHgvprZ

spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

queue:
  twitter: twitter-stream
exchange:
  twitter: twitter-exchange
routing_key:
  track: track.*

server:
  port: 8081

info:
  project: "twitter-gathering"
  kotlin: @kotlin.version@

management:
  endpoints:
    web:
      expose: "*"

---

spring:
  profiles: docker
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    port: 5672

twitter:
  consumer-key: ${CONSUMER_KEY}
  consumer-secret: ${CONSUMER_SECRET}
  access-token: ${ACCESS_TOKEN}
  access-token-secret: ${ACCESS_TOKEN_SECRET}

queue:
  twitter: twitter-stream
exchange:
  twitter: twitter-exchange
routing_key:
  track: track.*

server:
  port: 8081

info:
  project: "twitter-gathering"
  kotlin: @kotlin.version@

management:
  endpoints:
    web:
      expose: "*"